config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "items#index"


  resources :items, only: %i[show new create edit update destroy] do
    resources :rentals, only: :create
  end

  resources :rentals, only: %i[destroy]

  get '/about_us', to: "pages#about_us"
  get '/contact_us', to: "pages#contact_us"
  post '/contact_us', to: "pages#create"
  get '/terms_of_services', to: "pages#terms_of_services"

  get '/dashboard', to: 'dashboard#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_one_attached :photo

  validates :name, :brand, :description, :size, :price, :photo, presence: true
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :item
  belongs_to :user
  validates :start_date, :end_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :rentals
  has_many :items
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
    @my_rentals = @user.rentals
    @my_uploaded_items = @user.items
  end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :find_item, only: [:show]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @items = Item.all.order(created_at: :desc)
    if params[:query].present?
      subquery = <<~SQL
        name @@ :query
        OR brand @@ :query
        OR description @@ :query
      SQL
      @items = @items.where(subquery, query: "%#{params[:query]}%")
    end
  end

  def show
    @rental = Rental.new
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.user = current_user
    if @item.save
      redirect_to item_path(@item)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    find_item
  end

  def update
    find_item
    @item.update(item_params)
    redirect_to item_path(@item)
  end

  def destroy
    find_item
    @item.destroy
    redirect_to dashboard_path, status: :see_other
  end

  private

  def find_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :brand, :size, :price, :photo, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[about_us contact_us terms_of_services]
  
  def create
    redirect_to root_path, notice: "Your message has been successfully sent ❤️"
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  # creating a new item rental

  def create
    @item = Item.find(params[:item_id])
    @rental = Rental.new(rental_params)
    @rental.item = @item
    @rental.user = current_user
    if @rental.save
      # redirect
      redirect_to dashboard_path,  notice: "Your rental has been confirmed for the total amount of #{(@rental.end_date - @rental.start_date).to_i / 60 / 60 / 24 * @item.price} EUR"
    else
      render "items/show", notice: 'Something went wrong with your rent request', status: :unprocessable_entity
    end
  end

  def destroy
    @rental = Rental.find(params[:id])
    @rental.destroy
    redirect_to dashboard_path, notice: 'Your rental has been cancelled'
  end

  private

  def rental_params
    params.require(:rental).permit(:start_date, :end_date)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/show.html.erb
<div>
  <h2 class="pt-4 pb-2 m-0 text-center fw-normal" >Welcome, <%= @user.username %></h2>
  <hr>

  <div class="my-4">
    <h5 class="fw-light fst-italic py-4 fw-normal">Items you have rented:</h5>

    <% @my_rentals.each do |rental| %>
      <div class="card h-60 border border-0">
        <div class="card-body d-flex ps-0">
          <% if rental.item.photo.attached? %>
            <%= link_to item_path(rental.item) do %>
              <%= cl_image_tag rental.item.photo.key, height: 300, width: 300, crop: :fill, class: "rounded-2" %>
            <% end %>
          <% else %>
            <img src="https://upload.wikimedia.org/wikipedia/commons/1/14/No_Image_Available.jpg" alt="No image available" class="img-fluid img-thumbnail rounded-4">
          <% end %>
          <div class="card-info ms-4 ps-4">
            <h4> <%= link_to "#{rental.item.name}", item_path(rental.item) %></h4>
            <p><%= rental.item.description %></p>
            <p>Renting from <%= rental.start_date.strftime("%d-%m-%y") %> to <%= rental.end_date.strftime("%d-%m-%y") %></p>
            <p>Total amount: <%= (rental.end_date - rental.start_date).to_i / 60 / 60 / 24 * rental.item.price %> EUR</p>
            <%= link_to "Cancel", rental_path(rental), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-dark rounded-4 mt-4"%>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="my-4">
    <h5 class="fw-light fst-italic py-4 fw-normal">Items you have uploaded:</h5>

    <% @my_uploaded_items.each do |item| %>
        <div class="card h-60 border border-0">
          <div class="card-body d-flex ps-0">
            <% if item.photo.attached? %>
                <%= link_to item_path(item) do %>
                  <%= cl_image_tag item.photo.key, height: 300, width: 300, crop: :fill, class: "rounded-2" %>
                <% end %>
            <% else %>
              <img src="https://upload.wikimedia.org/wikipedia/commons/1/14/No_Image_Available.jpg" alt="No image available" class="img-fluid img-thumbnail rounded-4">
            <% end %>
            <div class="card-info ms-4 ps-4">
              <h4> <%= link_to "#{item.name}", item_path(item) %></h4>
              <p><%= item.description %></p>
              <p><%= item.price %> EUR / day</p>
              <%= link_to "Edit", edit_item_path(item), class: "btn btn-dark rounded-4 mt-4"%>
              <%= link_to "Delete", item_path(item), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-dark rounded-4 mt-4"%>
            </div>
          </div>
        </div>
    <% end %>
  </div>

</div>

app/views/items/_form.html.erb
<div class="container bs5-grid-row p-0">
  <%= simple_form_for [@item] do |f| %>
    <%= f.input :name %>
    <%= f.input :brand %>
    <%= f.input :description %>
    <%= f.input :size, :collection => %w[XS S M L XL XXL] %>
    <%= f.input :price %>
    <%= f.input :photo, as: :file %>
    <%= f.button :submit, class: "btn btn-dark rounded-4 mt-3" %>
  <% end %>
</div>

app/views/items/edit.html.erb
<div class="container p-0">
  <h2 class="mb-5">Edit your item</h2>
  <%= render 'form' %>
</div>

app/views/items/index.html.erb
  <div class="banner d-flex align-items-center" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1544957992-20514f595d6f?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D);">
    <div class="container text-center" >
      <h1>CIRCLE</h1>
      <p>The circular fashion renting experience</p>
    </div>
  </div>

<h2>All Products</h2>

<div class="mt-5 row my-2 d-flex flex-wrap">
  <% @items.each do |item| %>
    <div class="col-sm-12 col-md-6 col-lg-3 mb-4">
      <div>
        <%= link_to item_path(item) do %>
          <%= cl_image_tag item.photo.key, class: 'image-cover', height: 250 %>
        <% end %>
        <div class="mt-4">
          <h5 class="card-title"><%= item.name %></h5>
          <p id="hidde-description" class="card-description"><%= item.description %></p>
        </div>
        <div>
          <p class="card-price">Rent from: <%= item.price %> EUR / day</p>
          <%= link_to "Details", item_path(item), class: "btn btn-dark rounded-4 mb-3" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/items/new.html.erb
<div class="container p-0">
  <h2 class="mb-5">Add an item</h2>
  <%= render 'form' %>
</div>

app/views/items/show.html.erb
<div class="d-flex row">
  <div  class="col-sm-12 col-lg-6 mt-4">
    <% if @item.photo.attached? %>
      <%= cl_image_tag @item.photo.key, id:"image-show", width: 1200, class: "img-fluid" %>
    <% else %>
      <img src="https://upload.wikimedia.org/wikipedia/commons/1/14/No_Image_Available.jpg" alt="No image available" class="img-fluid img-thumbnail rounded-4">
    <% end %>
  </div>
  <div class="card border border-0 col-sm-12 col-lg-6 mt-4">
    <div class="card-body p-0">
      <h2 class="pb-4 mt-0"><%= @item.name.capitalize %></h2>
      <h5 class="pb-3 fw-lighter text-muted">Brand: <%= @item.brand %></h5>
      <h5 class="pb-2 fw-lighter text-muted">Size: <%= @item.size %></h5>
      <p class="pb-3 text-muted"><%= @item.description %></p>
      <h5 class="pb-4 fw-light">Rent from: <%= @item.price %> EUR / day</h5>

      <% if @item.user == current_user %>
        <p class="pb-2 fw-normal">This beautiful item is yours! </p>
        <%= link_to "Edit", edit_item_path(@item), class: "btn btn-dark rounded-4" %>
        <%= link_to "Delete", item_path(@item), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-dark rounded-4" %>

      <% else %>
        <%# Here we want to show a form with the dates the user wants to rent %>
        <div >
          <%= simple_form_for [@item, @rental] do |f| %>
            <%= f.input :start_date,
            as: :string,
            input_html: { data: { controller: "datepicker" } } %>
            <%= f.input :end_date,
            as: :string,
            input_html: { data: { controller: "datepicker" } } %>
            <%= f.submit "Request rental", class: "btn btn-dark rounded-4" %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Circle</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  </head>

  <body>
  <div class="container">
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <div class="main-content">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </div>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_with scope: :contact_form, url: contact_us_path, method: :post, local: true, class: "container" do |form| %>
    <%= form.hidden_field :waza %>
    <div class="form-group mb-3">
      <%= form.label :name, class: "mb-2" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group mb-3">
      <%= form.label :last_name, class: "mb-2" %>
      <%= form.text_field :last_name, class: "form-control" %>
    </div>
    <div class="form-group mb-3">
      <%= form.label :email, class: "mb-2" %>
      <%= form.email_field :email, class: "form-control" %>
    </div>
    <div class="form-group mb-3">
      <%= form.label :message, class: "mb-2" %>
      <%= form.text_area :message, class: "form-control" %>
    </div>
    <%= form.submit "Submit", class: "btn btn-dark rounded-4 mt-4" %>
  <% end %>

app/views/pages/about_us.html.erb
<div class="container p-0">
  <h2 class="mb-5">About us</h2>
    <div class="row justify-content-center">
      <div id="image_team" class="col-sm-12 col-lg-6">
        <%= image_tag "IMG_0995_BW.jpg", alt: "❤️ BEST TEAM EVER ❤️",widht: 600, height: 600, class: "img-fluid img-thumbnail border border-0" %>

      </div>
      <div class="card px-4 border border-0 col-sm-12 col-lg-6">
        <h3 id="the_title" class="tos">Hold on to your butts</h3>
        <p>Look, just because I don't be givin' no man a foot massage don't make it right for Marsellus to throw Antwone into a glass motherfuckin' house, fuckin' up the way the nigger talks. Motherfucker do that shit to me, he better paralyze my ass, 'cause I'll kill the motherfucker, know what I'm sayin'? </p>
        <h3 class="tos">I can do that</h3>
        <p>Normally, both your asses would be dead as fucking fried chicken, but you happen to pull this shit while I'm in a transitional period so I don't wanna kill you, I wanna help you. But I can't give you this case, it don't belong to me. Besides, I've already been through too much shit this morning over this case to hand it over to your dumb ass. </p>
      </div>
    </div>
</div>

app/views/pages/contact_us.html.erb
<div class="container bs5-grid-row p-0">
  <h2 class="mb-5">Contact</h2>
  <%= render 'form' %>
</div>

<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <%= value %>
  </div>
<% end %>

app/views/pages/terms_of_services.html.erb
<div class="container p-0">
  <h2 class="mb-5">Terms of Services</h2>
  <div>
    <h3 class="tos">Terms and Conditions
    </br>General Site Usage
    </br>Last Revised: December 16, 2023</h3>

    <p class="mt-2">Welcome to www.lorem-ipsum.info. This site is provided as a service to our visitors and may be used for informational purposes only. Because the Terms and Conditions contain legal obligations, please read them carefully.</p>

    <h3 class="tos">1. YOUR AGREEMENT</h3>
    <p class="mt-2">By using this Site, you agree to be bound by, and to comply with, these Terms and Conditions. If you do not agree to these Terms and Conditions, please do not use this site.</p>
    <p class="mt-2">PLEASE NOTE: We reserve the right, at our sole discretion, to change, modify or otherwise alter these Terms and Conditions at any time. Unless otherwise indicated, amendments will become effective immediately. Please review these Terms and Conditions periodically. Your continued use of the Site following the posting of changes and/or modifications will constitute your acceptance of the revised Terms and Conditions and the reasonableness of these standards for notice of changes. For your information, this page was last updated as of the date at the top of these terms and conditions.</p>

    <h3 class="tos">2. PRIVACY</h3>
    <p class="mt-2">Please review our Privacy Policy, which also governs your visit to this Site, to understand our practices.</p>

    <h3 class="tos">3. LINKED SITES</h3>
    <p class="mt-2">This Site may contain links to other independent third-party Web sites ("Linked Sites”). These Linked Sites are provided solely as a convenience to our visitors. Such Linked Sites are not under our control, and we are not responsible for and does not endorse the content of such Linked Sites, including any information or materials contained on such Linked Sites. You will need to make your own independent judgment regarding your interaction with these Linked Sites.</p>

    <h3 class="tos">4. FORWARD LOOKING STATEMENTS</h3>
    <p class="mt-2">All materials reproduced on this site speak as of the original date of publication or filing. The fact that a document is available on this site does not mean that the information contained in such document has not been modified or superseded by events or by a subsequent document or filing. We have no duty or policy to update any information or statements contained on this site and, therefore, such information or statements should not be relied upon as being current as of the date you access this site.</p>

    <h3 class="tos">5. DISCLAIMER OF WARRANTIES AND LIMITATION OF LIABILITY</h3>
    <ul class="tos">
      <li class="tos">A. THIS SITE MAY CONTAIN INACCURACIES AND TYPOGRAPHICAL ERRORS. WE DOES NOT WARRANT THE ACCURACY OR COMPLETENESS OF THE MATERIALS OR THE RELIABILITY OF ANY ADVICE, OPINION, STATEMENT OR OTHER INFORMATION DISPLAYED OR DISTRIBUTED THROUGH THE SITE. YOU EXPRESSLY UNDERSTAND AND AGREE THAT: (i) YOUR USE OF THE SITE, INCLUDING ANY RELIANCE ON ANY SUCH OPINION, ADVICE, STATEMENT, MEMORANDUM, OR INFORMATION CONTAINED HEREIN, SHALL BE AT YOUR SOLE RISK; (ii) THE SITE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS; (iii) EXCEPT AS EXPRESSLY PROVIDED HEREIN WE DISCLAIM ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, WORKMANLIKE EFFORT, TITLE AND NON-INFRINGEMENT; (iv) WE MAKE NO WARRANTY WITH RESPECT TO THE RESULTS THAT MAY BE OBTAINED FROM THIS SITE, THE PRODUCTS OR SERVICES ADVERTISED OR OFFERED OR MERCHANTS INVOLVED; (v) ANY MATERIAL DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE SITE IS DONE AT YOUR OWN DISCRETION AND RISK; and (vi) YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR FOR ANY LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY SUCH MATERIAL.</li>
      <li class="tos">B. YOU UNDERSTAND AND AGREE THAT UNDER NO CIRCUMSTANCES, INCLUDING, BUT NOT LIMITED TO, NEGLIGENCE, SHALL WE BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE OR CONSEQUENTIAL DAMAGES THAT RESULT FROM THE USE OF, OR THE INABILITY TO USE, ANY OF OUR SITES OR MATERIALS OR FUNCTIONS ON ANY SUCH SITE, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THE FOREGOING LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.</li>
    </ul>

    <h3 class="tos">6. EXCLUSIONS AND LIMITATIONS</h3>
    <p class="mt-2">SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES OR THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES. ACCORDINGLY, OUR LIABILITY IN SUCH JURISDICTION SHALL BE LIMITED TO THE MAXIMUM EXTENT PERMITTED BY LAW.</p>

    <h3 class="tos">7. OUR PROPRIETARY RIGHTS</h3>
    <p class="mt-2">This Site and all its Contents are intended solely for personal, non-commercial use. Except as expressly provided, nothing within the Site shall be construed as conferring any license under our or any third party's intellectual property rights, whether by estoppel, implication, waiver, or otherwise. Without limiting the generality of the foregoing, you acknowledge and agree that all content available through and used to operate the Site and its services is protected by copyright, trademark, patent, or other proprietary rights. You agree not to: (a) modify, alter, or deface any of the trademarks, service marks, trade dress (collectively "Trademarks") or other intellectual property made available by us in connection with the Site; (b) hold yourself out as in any way sponsored by, affiliated with, or endorsed by us, or any of our affiliates or service providers; (c) use any of the Trademarks or other content accessible through the Site for any purpose other than the purpose for which we have made it available to you; (d) defame or disparage us, our Trademarks, or any aspect of the Site; and (e) adapt, translate, modify, decompile, disassemble, or reverse engineer the Site or any software or programs used in connection with it or its products and services.
    The framing, mirroring, scraping or data mining of the Site or any of its content in any form and by any method is expressly prohibited.</p>

    <h3 class="tos">8. INDEMNITY</h3>
    <p class="mt-2">By using the Site web sites you agree to indemnify us and affiliated entities (collectively "Indemnities") and hold them harmless from any and all claims and expenses, including (without limitation) attorney's fees, arising from your use of the Site web sites, your use of the Products and Services, or your submission of ideas and/or related materials to us or from any person's use of any ID, membership or password you maintain with any portion of the Site, regardless of whether such use is authorized by you.</p>

    <h3 class="tos">9. COPYRIGHT AND TRADEMARK NOTICE</h3>
    <p class="mt-2">Except our generated dummy copy, which is free to use for private and commercial use, all other text is copyrighted. generator.lorem-ipsum.info © 2013, all rights reserved</p>

    <h3 class="tos">10. INTELLECTUAL PROPERTY INFRINGEMENT CLAIMS</h3>
    <p class="mt-2">It is our policy to respond expeditiously to claims of intellectual property infringement. We will promptly process and investigate notices of alleged infringement and will take appropriate actions under the Digital Millennium Copyright Act ("DMCA") and other applicable intellectual property laws. Notices of claimed infringement should be directed to:
    generator.lorem-ipsum.info</p>
    <ul class="tos">
      <li class="tos">126 Electricov St.</li>
      <li class="tos">Kiev, Kiev 04176</li>
      <li class="tos">Ukraine</li>
      <li class="tos">contact@lorem-ipsum.info</li>
    </ul>

    <h3 class="tos">11. PLACE OF PERFORMANCE</h3>
    <p class="mt-2">This Site is controlled, operated and administered by us from our office in Kiev, Ukraine. We make no representation that materials at this site are appropriate or available for use at other locations outside of the Ukraine and access to them from territories where their contents are illegal is prohibited. If you access this Site from a location outside of the Ukraine, you are responsible for compliance with all local laws.</p>

    <h3 class="tos">12. GENERAL</h3>
    <ul class="tos">
      <li class="tos">A. If any provision of these Terms and Conditions is held to be invalid or unenforceable, the provision shall be removed (or interpreted, if possible, in a manner as to be enforceable), and the remaining provisions shall be enforced. Headings are for reference purposes only and in no way define, limit, construe or describe the scope or extent of such section. Our failure to act with respect to a breach by you or others does not waive our right to act with respect to subsequent or similar breaches. These Terms and Conditions set forth the entire understanding and agreement between us with respect to the subject matter contained herein and supersede any other agreement, proposals and communications, written or oral, between our representatives and you with respect to the subject matter hereof, including any terms and conditions on any of customer's documents or purchase orders.</li>
      <li class="tos">B. No Joint Venture, No Derogation of Rights. You agree that no joint venture, partnership, employment, or agency relationship exists between you and us as a result of these Terms and Conditions or your use of the Site. Our performance of these Terms and Conditions is subject to existing laws and legal process, and nothing contained herein is in derogation of our right to comply with governmental, court and law enforcement requests or requirements relating to your use of the Site or information provided to or gathered by us with respect to such use.</li>
    </ul>
  </div>
</div>

app/views/rental/_form.html.erb
<div class="container bs5-grid-row">
  <%= simple_form_for [@item, @rental] do |f| %>
    <%= f.input :start_date %>
    <%= f.input :end_date %>
    <%= f.submit %>
  <% end %>
</div>

app/views/rental/create.html.erb
<%= render "form", rental: @rental %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<hr>
<div class="footer container mt-5 d-flex justify-content-between">
  <div class="d-flex align-items-start flex-column mb-4">
    <div class="d-flex align-items-center justify-content-center mb-auto">
      <%= link_to root_path, class: 'navbar-brand' do %>
        <div class="d-flex align-items-center">
          <%= image_tag "CIRCLE_logo.png", class: 'logo'%>
          <h3 class="m-0 ps-2">CIRCLE</h3>
        </div>
      <% end %>
    </div>
    <div>
      <ul class="footer-circle d-flex">
        <li class="me-4"><a href="https://www.facebook.com/" target="_blank"><i class="fa-brands fa-facebook"></i></a></li>
        <li class="me-4"><a href="https://www.linkedin.com/" target="_blank"><i class="fa-brands fa-linkedin"></i></a></li>
        <li class="me-4"><a href="https://www.youtube.com/" target="_blank"><i class="fa-brands fa-youtube"></i></a></li>
        <li class="me-4"><a href="https://www.instagram.com/" target="_blank"><i class="fa-brands fa-instagram"></i></a></li>
      </ul>
    </div>
  </div>
  <div>
    <ul class="footer-link text-end">
      <%= link_to about_us_path do %>
      <li class="mb-4">About Us</li>
      <% end %>
      <%= link_to contact_us_path do %>
      <li class="mb-4">Contact</li>
      <% end %>
      <%= link_to terms_of_services_path do %>
      <li class="mb-4">Terms of Service</li>
      <% end %>
    </ul>
  </div>
</div>